### ISSUE TITLE
Build action

### ISSUE THREAD

**Issue by eroshenkoam** [qagid/github-actions#3]
.github/workflows/build.yml
```
name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "Compile"
        run: ./gradlew compileTestJava
      - name: "Test"
        run: ./gradlew test
```
