### ISSUE TITLE
Labeler action

### ISSUE THREAD

**Issue by eroshenkoam** [qagid/github-actions#4]
.github/labeler.yml
```
theme:workflow:
  - ".github/**"

theme:build:
  - "gradle/**"
  - "build.gradle.kts"
  - "gradle.properties"
  - ".gitignore"

theme:core:
  - "src/main/*"

theme:tests:
  - "src/test/*"
```

.github/workflows/labeler.yml
```
name: "Add theme labels"

on:
  - pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```
