### ISSUE TITLE
Labels verify action

### ISSUE THREAD

**Issue by eroshenkoam** [qagid/github-actions#5]
.github/workflows/label-verify.yml
```
name: "Verify type labels"

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: zwaldowski/match-label-action@v2
        with:
          allowed: 'type:fix, type:new, type:other'
```
