### ISSUE TITLE
Release draft action

### ISSUE THREAD

**Issue by eroshenkoam** [qagid/github-actions#6]
.github/workflows/release-draft.yml
```
name: Release Draft

on:
  push:
    branches:
      - master

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
